#!/bin/bash

[ -d "/mnt/c" ] && [[ "$(uname -a)" == *microsoft* ]] && {
    export SCOOP=${SCOOP:-"/mnt/d/tool/scoop"}
    export PATH=$PATH:$SCOOP/shims
    alias cmd='/mnt/c/Windows/System32/cmd.exe'
    alias adb='$SCOOP/shims/adb.exe'
    alias fastboot='$SCOOP/shims/fastboot.exe'
    function cmd() {
        /mnt/c/Windows/System32/cmd.exe $@
    }
    function adb() {
        $SCOOP/shims/adb.exe $@
    }
    function fastboot() {
        $SCOOP/shims/fastboot.exe $@
    }
}
