# https://just.systems
set unstable
set default-script
set script-interpreter := ["bash", "-euo", "pipefail"]

os := os()
py := if os == "windows" { "python" } else { "python3" }

run file="":
    file="{{file}}"
    ext="${file##*.}"
    if [ "$ext" = "sh" ]; then
        bash "$file"
    elif [ "$ext" = "py" ]; then
        {{py}} "$file"
    elif [ "$ext" = "go" ]; then
        go run "$file"
    else
        echo "Unsupported extension: $ext"
    fi
