name: ccls

on:
  schedule:
  - cron: '0 2 * * *'
  push:
    branches: [ master, test ]
  workflow_dispatch:

jobs:
  linux:
    runs-on: ubuntu-18.04
    steps:
      - name: Download llvm
        run: |
          ver=$(curl -s "https://github.com/llvm/llvm-project/releases/latest" | grep -Po "(\d+\.){2}\d+")
          ver=12.0.1
          wget -Ollvm.tar.xz "https://github.com/llvm/llvm-project/releases/download/llvmorg-${ver}/clang+llvm-${ver}-x86_64-linux-gnu-ubuntu-16.04.tar.xz"
          tar xJf llvm.tar.xz
          mv clang+llvm-${ver}-x86_64-linux-gnu-ubuntu- llvm
      - name: Build ccls
        run: |
          git clone --depth=1 --recursive https://github.com/MaskRay/ccls
          cd ccls
          cmake -H. -BRelease -DCMAKE_BUILD_TYPE=Release -DCMAKE_PREFIX_PATH=../llvm -DCMAKE_CXX_FLAGS="-static-libgcc -static-libstdc++"
          cmake --build Release -j
          mv Release/ccls .
          zip -9 ../ccls_linux_amd64.zip ./ccls
      - uses: actions/upload-artifact@v2
        with:
          name: ccls_linux
          path: ./ccls_linux_amd64.zip
          retention-days: 1
  publish:
    needs: [linux]
    runs-on: ubuntu-18.04
    steps:
      - uses: dev-drprasad/delete-tag-and-release@v0.2.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          delete_release: true
          tag_name: ccls
      - uses: actions/download-artifact@v2
      - name: Ls
        run: ls -la
      - uses: meeDamian/github-release@v2.0.3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: ccls
          name: ccls
          allow_override: true
          gzip: false
          draft: false
          files: |
            ccls_linux_amd64.zip:./ccls_linux/ccls_linux_amd64.zip
          body: |
            ### Requirement
              os >= ubuntu 14.04
              or
              glibc >= 2.17


